### ISSUE TITLE
cannot access standard Hexo fields?

### ISSUE THREAD

**Issue by ghost** [loehnertz/hexo-custom-fields#1]
Hi, this is a great plugin. thanks!
Try as I might I can't access the 'tags' field from my post. I can access a field called 'foo' with the same content as my tags field. I also can't access 'categories'. In the README you mention that one can use all the standard hexo fields, but it's not clear to me how to address them. From your code I can't make out why it isn't  finding these fields. Any ideas?

Thanks!

**Comment by ghost** [comment]
hmm, I see it isn't included in the object that hexo returns, so maybe this isn't an issue with this library.

**Comment by loehnertz** [comment]
I'll look into it as well, but it seems then that Hexo is just not offering it.
Thanks for the praise though 😊
If you miss any features, let me know!
